backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "blog_post"
    label: "Публикации"
    folder: "site/content/blog-post"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Подзаголовок", name: "subtitle", widget: "string"}
      - {label: "Дата публиуации", name: "date", widget: "datetime"}
      - {label: "Вводное описание", name: "description", widget: "text"}
      - {label: "Изображение", name: "image", widget: "image", required: false}
      - {label: "Содержимое", name: "body", widget: "markdown"}
  - name: "event"
    label: "Анонсы"
    folder: "site/content/events"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Подзаголовок", name: "subtitle", widget: "string"}
      - {label: "Дата и время проведения", name: "event_date", widget: "datetime"}
      - {label: "Краткое описание", name: "description", widget: "text"}
      - {label: "Изображение", name: "image", widget: "image", required: false}
      - {label: "Содержимое", name: "body", widget: "markdown"}
  - name: "courses"
    label: "Курсы"
    folder: "site/content/coursees"
    create: true
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Подзаголовок", name: "subtitle", widget: "string"}
      - {label: "Дата и время проведения", name: "event_date", widget: "datetime"}
      - {label: "Краткое описание", name: "description", widget: "text"}
      - {label: "Изображение", name: "image", widget: "image", required: false}
      - {label: "Содержимое", name: "body", widget: "markdown"}
